In [54]:
import pandas as pd
import numpy as np

In [55]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': [
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South'
    ],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': [
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice'
    ]
}
df=pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    371     60   John
1  2023-01-02       B   West    743     93   Mary
2  2023-01-03       C  North    613     66    Bob
3  2023-01-04       D  South    960     44  Alice
4  2023-01-05       A   East    427     62   John
5  2023-01-06       B   West    192     63   Mary
6  2023-01-07       C  North    416     19    Bob
7  2023-01-08       D  South    229     58  Alice
8  2023-01-09       A   East    460     13   John
9  2023-01-10       B   West    739     59   Mary
10 2023-01-11       C  North    281     59    Bob
11 2023-01-12       D  South    456     91  Alice
12 2023-01-13       A   East    825     18   John
13 2023-01-14       B   West    951     86   Mary
14 2023-01-15       C  North    424     32    Bob
15 2023-01-16       D  South    672     60  Alice
16 2023-01-17       A   East    553     26   John
17 2023-01-18       B   West    399     44   Mary
18 2023-01-19       C  North    934     69    Bob
19 2023-01-20       D  South    476     50  Alice

In [56]:
pd.pivot_table(df,values='Sales', index='Region',columns='Product')

Product      A      B      C      D
Region
East     527.2    NaN    NaN    NaN
North      NaN    NaN  533.6    NaN
South      NaN    NaN    NaN  558.6
West       NaN  604.8    NaN    NaN

In [57]:
pd.pivot_table(df,values=['Sales','Units'], index='Region',columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     527.2    NaN    NaN    NaN  35.8   NaN   NaN   NaN
North      NaN    NaN  533.6    NaN   NaN   NaN  49.0   NaN
South      NaN    NaN    NaN  558.6   NaN   NaN   NaN  60.6
West       NaN  604.8    NaN    NaN   NaN  69.0   NaN   NaN

In [58]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

Basic Operation

In [59]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [60]:
df1.shape

(5, 3)

In [61]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [62]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [63]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [64]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [65]:
def square(x):
    return x*x

In [66]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [67]:
df1['D']=df1['B'].apply(square)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [71]:
df1['E']=df1['B'].apply(lambda x:x**2)
df1

   A   B    C     D     E
0  1  10  100   100   100
1  2  20  200   400   400
2  3  30  300   900   900
3  4  40  400  1600  1600
4  5  50  500  2500  2500